// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/kk-server.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/kk-server.go -destination=internal/transport/mocks/kk_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "mko/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKKServiceInterface is a mock of KKServiceInterface interface.
type MockKKServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKKServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockKKServiceInterfaceMockRecorder is the mock recorder for MockKKServiceInterface.
type MockKKServiceInterfaceMockRecorder struct {
	mock *MockKKServiceInterface
}

// NewMockKKServiceInterface creates a new mock instance.
func NewMockKKServiceInterface(ctrl *gomock.Controller) *MockKKServiceInterface {
	mock := &MockKKServiceInterface{ctrl: ctrl}
	mock.recorder = &MockKKServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKKServiceInterface) EXPECT() *MockKKServiceInterfaceMockRecorder {
	return m.recorder
}

// ConfigureExchange mocks base method.
func (m *MockKKServiceInterface) ConfigureExchange(ctx context.Context, cfg domain.ExchangeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureExchange", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureExchange indicates an expected call of ConfigureExchange.
func (mr *MockKKServiceInterfaceMockRecorder) ConfigureExchange(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureExchange", reflect.TypeOf((*MockKKServiceInterface)(nil).ConfigureExchange), ctx, cfg)
}

// ConfigureKK mocks base method.
func (m *MockKKServiceInterface) ConfigureKK(ctx context.Context, cfg domain.KKConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureKK", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureKK indicates an expected call of ConfigureKK.
func (mr *MockKKServiceInterfaceMockRecorder) ConfigureKK(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureKK", reflect.TypeOf((*MockKKServiceInterface)(nil).ConfigureKK), ctx, cfg)
}

// RunExchange mocks base method.
func (m *MockKKServiceInterface) RunExchange(ctx context.Context, cmd domain.RunExchangeCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunExchange", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunExchange indicates an expected call of RunExchange.
func (mr *MockKKServiceInterfaceMockRecorder) RunExchange(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunExchange", reflect.TypeOf((*MockKKServiceInterface)(nil).RunExchange), ctx, cmd)
}

// SubscribeExchangeResults mocks base method.
func (m *MockKKServiceInterface) SubscribeExchangeResults(ctx context.Context, boardID string) (<-chan domain.ExchangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeExchangeResults", ctx, boardID)
	ret0, _ := ret[0].(<-chan domain.ExchangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExchangeResults indicates an expected call of SubscribeExchangeResults.
func (mr *MockKKServiceInterfaceMockRecorder) SubscribeExchangeResults(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExchangeResults", reflect.TypeOf((*MockKKServiceInterface)(nil).SubscribeExchangeResults), ctx, boardID)
}
