// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/ou-server.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/ou-server.go -destination=internal/transport/mocks/ou_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "mko/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOuServiceInterface is a mock of OuServiceInterface interface.
type MockOuServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOuServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockOuServiceInterfaceMockRecorder is the mock recorder for MockOuServiceInterface.
type MockOuServiceInterfaceMockRecorder struct {
	mock *MockOuServiceInterface
}

// NewMockOuServiceInterface creates a new mock instance.
func NewMockOuServiceInterface(ctrl *gomock.Controller) *MockOuServiceInterface {
	mock := &MockOuServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOuServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOuServiceInterface) EXPECT() *MockOuServiceInterfaceMockRecorder {
	return m.recorder
}

// ConfigureOu mocks base method.
func (m *MockOuServiceInterface) ConfigureOu(ctx context.Context, cfg domain.OuConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureOu", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureOu indicates an expected call of ConfigureOu.
func (mr *MockOuServiceInterfaceMockRecorder) ConfigureOu(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureOu", reflect.TypeOf((*MockOuServiceInterface)(nil).ConfigureOu), ctx, cfg)
}

// GetVersion mocks base method.
func (m *MockOuServiceInterface) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockOuServiceInterfaceMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockOuServiceInterface)(nil).GetVersion), ctx)
}

// Ping mocks base method.
func (m *MockOuServiceInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockOuServiceInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockOuServiceInterface)(nil).Ping), ctx)
}

// ReadOuSubaddress mocks base method.
func (m *MockOuServiceInterface) ReadOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, receiveArea bool) (domain.OuSubaddressData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOuSubaddress", ctx, board, sub, receiveArea)
	ret0, _ := ret[0].(domain.OuSubaddressData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOuSubaddress indicates an expected call of ReadOuSubaddress.
func (mr *MockOuServiceInterfaceMockRecorder) ReadOuSubaddress(ctx, board, sub, receiveArea any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOuSubaddress", reflect.TypeOf((*MockOuServiceInterface)(nil).ReadOuSubaddress), ctx, board, sub, receiveArea)
}

// SetOuResponseWord mocks base method.
func (m *MockOuServiceInterface) SetOuResponseWord(ctx context.Context, board domain.BoardID, index domain.McoIndex, channel domain.Channel, ouAddress, word int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOuResponseWord", ctx, board, index, channel, ouAddress, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOuResponseWord indicates an expected call of SetOuResponseWord.
func (mr *MockOuServiceInterfaceMockRecorder) SetOuResponseWord(ctx, board, index, channel, ouAddress, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOuResponseWord", reflect.TypeOf((*MockOuServiceInterface)(nil).SetOuResponseWord), ctx, board, index, channel, ouAddress, word)
}

// SubscribeOuCommands mocks base method.
func (m *MockOuServiceInterface) SubscribeOuCommands(ctx context.Context, board domain.BoardID) (<-chan domain.OuCommandEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOuCommands", ctx, board)
	ret0, _ := ret[0].(<-chan domain.OuCommandEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeOuCommands indicates an expected call of SubscribeOuCommands.
func (mr *MockOuServiceInterfaceMockRecorder) SubscribeOuCommands(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOuCommands", reflect.TypeOf((*MockOuServiceInterface)(nil).SubscribeOuCommands), ctx, board)
}

// WriteOuSubaddress mocks base method.
func (m *MockOuServiceInterface) WriteOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, sd []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOuSubaddress", ctx, board, sub, sd)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOuSubaddress indicates an expected call of WriteOuSubaddress.
func (mr *MockOuServiceInterfaceMockRecorder) WriteOuSubaddress(ctx, board, sub, sd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOuSubaddress", reflect.TypeOf((*MockOuServiceInterface)(nil).WriteOuSubaddress), ctx, board, sub, sd)
}
