from executors.errors import main_information_reading_executor_error


class MainInformationReadingExecutorConversionError(main_information_reading_executor_error.MainInformationReadingExecutorError):
    pass
