@startuml use_case

!theme plain

left to right direction

actor "Пользователь" as user

usecase "Получить версию драйвера" as get_version
usecase "Проверить соединение" as check_connection
usecase "Проверить работоспособность пульта" as get_hardware_status

usecase "Прочитать основную информацию" as read_main_info
usecase "Записать основную информацию" as write_main_info

usecase "Прочитать длительности приёма ПКУ" as read_pku
usecase "Настроить режим приёма одной ПКУ" as set_pku_mode

usecase "Выдать РК" as send_rk_by_index

user -- get_version
user -- check_connection
user -- get_hardware_status
user -- read_main_info
user -- write_main_info
user -- read_pku
user -- set_pku_mode
user -- send_rk_by_index

@enduml
