// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/ou-usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/ou-usecase.go -destination=internal/service/mocks/driver_ou_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "mko/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDriverOuClient is a mock of DriverOuClient interface.
type MockDriverOuClient struct {
	ctrl     *gomock.Controller
	recorder *MockDriverOuClientMockRecorder
	isgomock struct{}
}

// MockDriverOuClientMockRecorder is the mock recorder for MockDriverOuClient.
type MockDriverOuClientMockRecorder struct {
	mock *MockDriverOuClient
}

// NewMockDriverOuClient creates a new mock instance.
func NewMockDriverOuClient(ctrl *gomock.Controller) *MockDriverOuClient {
	mock := &MockDriverOuClient{ctrl: ctrl}
	mock.recorder = &MockDriverOuClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverOuClient) EXPECT() *MockDriverOuClientMockRecorder {
	return m.recorder
}

// ConfigureOu mocks base method.
func (m *MockDriverOuClient) ConfigureOu(ctx context.Context, cfg domain.OuConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureOu", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureOu indicates an expected call of ConfigureOu.
func (mr *MockDriverOuClientMockRecorder) ConfigureOu(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureOu", reflect.TypeOf((*MockDriverOuClient)(nil).ConfigureOu), ctx, cfg)
}

// GetVersion mocks base method.
func (m *MockDriverOuClient) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockDriverOuClientMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockDriverOuClient)(nil).GetVersion), ctx)
}

// Ping mocks base method.
func (m *MockDriverOuClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDriverOuClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDriverOuClient)(nil).Ping), ctx)
}

// ReadOuSubaddress mocks base method.
func (m *MockDriverOuClient) ReadOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, receiveArea bool) (domain.OuSubaddressData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOuSubaddress", ctx, board, sub, receiveArea)
	ret0, _ := ret[0].(domain.OuSubaddressData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOuSubaddress indicates an expected call of ReadOuSubaddress.
func (mr *MockDriverOuClientMockRecorder) ReadOuSubaddress(ctx, board, sub, receiveArea any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOuSubaddress", reflect.TypeOf((*MockDriverOuClient)(nil).ReadOuSubaddress), ctx, board, sub, receiveArea)
}

// SetOuResponseWord mocks base method.
func (m *MockDriverOuClient) SetOuResponseWord(ctx context.Context, board domain.BoardID, index domain.McoIndex, channel domain.Channel, ouAddress, word int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOuResponseWord", ctx, board, index, channel, ouAddress, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOuResponseWord indicates an expected call of SetOuResponseWord.
func (mr *MockDriverOuClientMockRecorder) SetOuResponseWord(ctx, board, index, channel, ouAddress, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOuResponseWord", reflect.TypeOf((*MockDriverOuClient)(nil).SetOuResponseWord), ctx, board, index, channel, ouAddress, word)
}

// SubscribeOuCommands mocks base method.
func (m *MockDriverOuClient) SubscribeOuCommands(ctx context.Context, board domain.BoardID) (<-chan domain.OuCommandEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOuCommands", ctx, board)
	ret0, _ := ret[0].(<-chan domain.OuCommandEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeOuCommands indicates an expected call of SubscribeOuCommands.
func (mr *MockDriverOuClientMockRecorder) SubscribeOuCommands(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOuCommands", reflect.TypeOf((*MockDriverOuClient)(nil).SubscribeOuCommands), ctx, board)
}

// WriteOuSubaddress mocks base method.
func (m *MockDriverOuClient) WriteOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, sd []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOuSubaddress", ctx, board, sub, sd)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOuSubaddress indicates an expected call of WriteOuSubaddress.
func (mr *MockDriverOuClientMockRecorder) WriteOuSubaddress(ctx, board, sub, sd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOuSubaddress", reflect.TypeOf((*MockDriverOuClient)(nil).WriteOuSubaddress), ctx, board, sub, sd)
}

// MockOuService is a mock of OuService interface.
type MockOuService struct {
	ctrl     *gomock.Controller
	recorder *MockOuServiceMockRecorder
	isgomock struct{}
}

// MockOuServiceMockRecorder is the mock recorder for MockOuService.
type MockOuServiceMockRecorder struct {
	mock *MockOuService
}

// NewMockOuService creates a new mock instance.
func NewMockOuService(ctrl *gomock.Controller) *MockOuService {
	mock := &MockOuService{ctrl: ctrl}
	mock.recorder = &MockOuServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOuService) EXPECT() *MockOuServiceMockRecorder {
	return m.recorder
}

// ConfigureOu mocks base method.
func (m *MockOuService) ConfigureOu(ctx context.Context, cfg domain.OuConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureOu", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureOu indicates an expected call of ConfigureOu.
func (mr *MockOuServiceMockRecorder) ConfigureOu(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureOu", reflect.TypeOf((*MockOuService)(nil).ConfigureOu), ctx, cfg)
}

// GetVersion mocks base method.
func (m *MockOuService) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockOuServiceMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockOuService)(nil).GetVersion), ctx)
}

// Ping mocks base method.
func (m *MockOuService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockOuServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockOuService)(nil).Ping), ctx)
}

// ReadOuSubaddress mocks base method.
func (m *MockOuService) ReadOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, receiveArea bool) (domain.OuSubaddressData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOuSubaddress", ctx, board, sub, receiveArea)
	ret0, _ := ret[0].(domain.OuSubaddressData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOuSubaddress indicates an expected call of ReadOuSubaddress.
func (mr *MockOuServiceMockRecorder) ReadOuSubaddress(ctx, board, sub, receiveArea any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOuSubaddress", reflect.TypeOf((*MockOuService)(nil).ReadOuSubaddress), ctx, board, sub, receiveArea)
}

// SetOuResponseWord mocks base method.
func (m *MockOuService) SetOuResponseWord(ctx context.Context, board domain.BoardID, index domain.McoIndex, channel domain.Channel, ouAddress, word int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOuResponseWord", ctx, board, index, channel, ouAddress, word)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOuResponseWord indicates an expected call of SetOuResponseWord.
func (mr *MockOuServiceMockRecorder) SetOuResponseWord(ctx, board, index, channel, ouAddress, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOuResponseWord", reflect.TypeOf((*MockOuService)(nil).SetOuResponseWord), ctx, board, index, channel, ouAddress, word)
}

// SubscribeOuCommands mocks base method.
func (m *MockOuService) SubscribeOuCommands(ctx context.Context, board domain.BoardID) (<-chan domain.OuCommandEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOuCommands", ctx, board)
	ret0, _ := ret[0].(<-chan domain.OuCommandEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeOuCommands indicates an expected call of SubscribeOuCommands.
func (mr *MockOuServiceMockRecorder) SubscribeOuCommands(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOuCommands", reflect.TypeOf((*MockOuService)(nil).SubscribeOuCommands), ctx, board)
}

// WriteOuSubaddress mocks base method.
func (m *MockOuService) WriteOuSubaddress(ctx context.Context, board domain.BoardID, sub uint32, sd []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOuSubaddress", ctx, board, sub, sd)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOuSubaddress indicates an expected call of WriteOuSubaddress.
func (mr *MockOuServiceMockRecorder) WriteOuSubaddress(ctx, board, sub, sd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOuSubaddress", reflect.TypeOf((*MockOuService)(nil).WriteOuSubaddress), ctx, board, sub, sd)
}
