// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/kk-service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/kk-service.go -destination=internal/service/mocks/kk_driver_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "mko/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKKService is a mock of KKService interface.
type MockKKService struct {
	ctrl     *gomock.Controller
	recorder *MockKKServiceMockRecorder
	isgomock struct{}
}

// MockKKServiceMockRecorder is the mock recorder for MockKKService.
type MockKKServiceMockRecorder struct {
	mock *MockKKService
}

// NewMockKKService creates a new mock instance.
func NewMockKKService(ctrl *gomock.Controller) *MockKKService {
	mock := &MockKKService{ctrl: ctrl}
	mock.recorder = &MockKKServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKKService) EXPECT() *MockKKServiceMockRecorder {
	return m.recorder
}

// ConfigureExchange mocks base method.
func (m *MockKKService) ConfigureExchange(ctx context.Context, cfg domain.ExchangeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureExchange", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureExchange indicates an expected call of ConfigureExchange.
func (mr *MockKKServiceMockRecorder) ConfigureExchange(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureExchange", reflect.TypeOf((*MockKKService)(nil).ConfigureExchange), ctx, cfg)
}

// ConfigureKK mocks base method.
func (m *MockKKService) ConfigureKK(ctx context.Context, cfg domain.KKConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureKK", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureKK indicates an expected call of ConfigureKK.
func (mr *MockKKServiceMockRecorder) ConfigureKK(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureKK", reflect.TypeOf((*MockKKService)(nil).ConfigureKK), ctx, cfg)
}

// RunExchange mocks base method.
func (m *MockKKService) RunExchange(ctx context.Context, cmd domain.RunExchangeCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunExchange", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunExchange indicates an expected call of RunExchange.
func (mr *MockKKServiceMockRecorder) RunExchange(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunExchange", reflect.TypeOf((*MockKKService)(nil).RunExchange), ctx, cmd)
}

// SubscribeExchangeResults mocks base method.
func (m *MockKKService) SubscribeExchangeResults(ctx context.Context, boardID string) (<-chan domain.ExchangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeExchangeResults", ctx, boardID)
	ret0, _ := ret[0].(<-chan domain.ExchangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExchangeResults indicates an expected call of SubscribeExchangeResults.
func (mr *MockKKServiceMockRecorder) SubscribeExchangeResults(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExchangeResults", reflect.TypeOf((*MockKKService)(nil).SubscribeExchangeResults), ctx, boardID)
}

// MockKKDriver is a mock of KKDriver interface.
type MockKKDriver struct {
	ctrl     *gomock.Controller
	recorder *MockKKDriverMockRecorder
	isgomock struct{}
}

// MockKKDriverMockRecorder is the mock recorder for MockKKDriver.
type MockKKDriverMockRecorder struct {
	mock *MockKKDriver
}

// NewMockKKDriver creates a new mock instance.
func NewMockKKDriver(ctrl *gomock.Controller) *MockKKDriver {
	mock := &MockKKDriver{ctrl: ctrl}
	mock.recorder = &MockKKDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKKDriver) EXPECT() *MockKKDriverMockRecorder {
	return m.recorder
}

// ConfigureExchange mocks base method.
func (m *MockKKDriver) ConfigureExchange(ctx context.Context, cfg domain.ExchangeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureExchange", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureExchange indicates an expected call of ConfigureExchange.
func (mr *MockKKDriverMockRecorder) ConfigureExchange(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureExchange", reflect.TypeOf((*MockKKDriver)(nil).ConfigureExchange), ctx, cfg)
}

// ConfigureMko mocks base method.
func (m *MockKKDriver) ConfigureMko(ctx context.Context, cfg domain.KKConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureMko", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureMko indicates an expected call of ConfigureMko.
func (mr *MockKKDriverMockRecorder) ConfigureMko(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureMko", reflect.TypeOf((*MockKKDriver)(nil).ConfigureMko), ctx, cfg)
}

// SendCommandRun mocks base method.
func (m *MockKKDriver) SendCommandRun(ctx context.Context, cmd domain.RunExchangeCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommandRun", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommandRun indicates an expected call of SendCommandRun.
func (mr *MockKKDriverMockRecorder) SendCommandRun(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommandRun", reflect.TypeOf((*MockKKDriver)(nil).SendCommandRun), ctx, cmd)
}

// SubscribeExchangeResults mocks base method.
func (m *MockKKDriver) SubscribeExchangeResults(ctx context.Context, boardID string) (<-chan domain.ExchangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeExchangeResults", ctx, boardID)
	ret0, _ := ret[0].(<-chan domain.ExchangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExchangeResults indicates an expected call of SubscribeExchangeResults.
func (mr *MockKKDriverMockRecorder) SubscribeExchangeResults(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExchangeResults", reflect.TypeOf((*MockKKDriver)(nil).SubscribeExchangeResults), ctx, boardID)
}
