// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pku_service.proto
#ifndef GRPC_pku_5fservice_2eproto__INCLUDED
#define GRPC_pku_5fservice_2eproto__INCLUDED

#include "pku_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace api {

class MainService final {
 public:
  static constexpr char const* service_full_name() {
    return "api.MainService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::api::CommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>> AsyncSendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>>(AsyncSendCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>> PrepareAsyncSendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>>(PrepareAsyncSendCommandRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>* AsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::CommandResponse>* PrepareAsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::api::CommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>> AsyncSendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>>(AsyncSendCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>> PrepareAsyncSendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>>(PrepareAsyncSendCommandRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, std::function<void(::grpc::Status)>) override;
      void SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>* AsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::CommandResponse>* PrepareAsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendCommand_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendCommand(::grpc::ServerContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendCommand() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCommand(::grpc::ServerContext* context, ::api::CommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::api::CommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendCommand<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendCommand() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::api::CommandRequest, ::api::CommandResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response) { return this->SendCommand(context, request, response); }));}
    void SetMessageAllocatorFor_SendCommand(
        ::grpc::MessageAllocator< ::api::CommandRequest, ::api::CommandResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::api::CommandRequest, ::api::CommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendCommand<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendCommand() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendCommand() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendCommand() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendCommand(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendCommand() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::api::CommandRequest, ::api::CommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::api::CommandRequest, ::api::CommandResponse>* streamer) {
                       return this->StreamedSendCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendCommand(::grpc::ServerContext* /*context*/, const ::api::CommandRequest* /*request*/, ::api::CommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::api::CommandRequest,::api::CommandResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendCommand<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendCommand<Service > StreamedService;
};

}  // namespace api


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_pku_5fservice_2eproto__INCLUDED
