// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pku_service.proto

#include "pku_service.pb.h"
#include "pku_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace api {

static const char* MainService_method_names[] = {
  "/api.MainService/SendCommand",
};

std::unique_ptr< MainService::Stub> MainService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MainService::Stub> stub(new MainService::Stub(channel, options));
  return stub;
}

MainService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendCommand_(MainService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MainService::Stub::SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::api::CommandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::CommandRequest, ::api::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendCommand_, context, request, response);
}

void MainService::Stub::async::SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::CommandRequest, ::api::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCommand_, context, request, response, std::move(f));
}

void MainService::Stub::async::SendCommand(::grpc::ClientContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::CommandResponse>* MainService::Stub::PrepareAsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::CommandResponse, ::api::CommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendCommand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::CommandResponse>* MainService::Stub::AsyncSendCommandRaw(::grpc::ClientContext* context, const ::api::CommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendCommandRaw(context, request, cq);
  result->StartCall();
  return result;
}

MainService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MainService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MainService::Service, ::api::CommandRequest, ::api::CommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MainService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::CommandRequest* req,
             ::api::CommandResponse* resp) {
               return service->SendCommand(ctx, req, resp);
             }, this)));
}

MainService::Service::~Service() {
}

::grpc::Status MainService::Service::SendCommand(::grpc::ServerContext* context, const ::api::CommandRequest* request, ::api::CommandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api
#include <grpcpp/ports_undef.inc>

