@startuml c_3

!include <C4/C4_Component>

!theme plain

UpdateElementStyle(Container, $borderColor="#000000", $fontColor="#000000", $bgColor="#ffffff")
UpdateElementStyle(Component, $borderColor="#000000", $fontColor="#000000", $bgColor="#ffffff")

System_Boundary(workplace, "Система взаимодействия с платами") {
    Container_Boundary(pku_service, "Микросервис для работы с RS-485") {
        Component(pku, "Обработка запросов", "")
    }
    Container(pku_driver, "Драйвер РК/ПКУ", "C++", "Обращается к плате РК/ПКУ")
}

Rel(pku, pku_driver, "Отправляет запросы")

@enduml