// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pku_driver.proto
#ifndef GRPC_pku_5fdriver_2eproto__INCLUDED
#define GRPC_pku_5fdriver_2eproto__INCLUDED

#include "pku_driver.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace pku {
namespace driver {
namespace v1 {

class PkuDriver final {
 public:
  static constexpr char const* service_full_name() {
    return "pku.driver.v1.PkuDriver";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> AsyncCheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(AsyncCheckConnectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> PrepareAsyncCheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(PrepareAsyncCheckConnectionRaw(context, request, cq));
    }
    // Статус железки: читает основную информацию пульта; success=true, если
    // ответ получен и без ошибок (пульт доступен), иначе false + причина.
    virtual ::grpc::Status GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> AsyncGetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(AsyncGetHardwareStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> PrepareAsyncGetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(PrepareAsyncGetHardwareStatusRaw(context, request, cq));
    }
    // Основная информация пульта (0x0000): чтение блока 151 слово (сетевые
    // настройки + идентификация) и запись RW-полей одним пакетом.
    virtual ::grpc::Status ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::ReadMemoryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>> AsyncReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>>(AsyncReadMainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>> PrepareAsyncReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>>(PrepareAsyncReadMainInfoRaw(context, request, cq));
    }
    virtual ::grpc::Status WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::pku::driver::v1::StandardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> AsyncWriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(AsyncWriteMainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> PrepareAsyncWriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(PrepareAsyncWriteMainInfoRaw(context, request, cq));
    }
    // Приём ПКУ (0x3003_0000): чтение длительностей ПКУ (RO).
    virtual ::grpc::Status ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::pku::driver::v1::ReadPkuResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>> AsyncReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>>(AsyncReadPkuRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>> PrepareAsyncReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>>(PrepareAsyncReadPkuRaw(context, request, cq));
    }
    // Настройка ПКУ (0x3003_0080): режим приёма каждого ПКУ (RW).
    virtual ::grpc::Status SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::pku::driver::v1::StandardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> AsyncSetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(AsyncSetPkuModeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> PrepareAsyncSetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(PrepareAsyncSetPkuModeRaw(context, request, cq));
    }
    // Выдача РК (0x3002): запись длительности по индексу.
    virtual ::grpc::Status SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::pku::driver::v1::StandardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> AsyncSendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(AsyncSendRkByIndexRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>> PrepareAsyncSendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>>(PrepareAsyncSendRkByIndexRaw(context, request, cq));
    }
    virtual ::grpc::Status GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::VersionInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>> AsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>>(AsyncGetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>> PrepareAsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>>(PrepareAsyncGetVersionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Статус железки: читает основную информацию пульта; success=true, если
      // ответ получен и без ошибок (пульт доступен), иначе false + причина.
      virtual void GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Основная информация пульта (0x0000): чтение блока 151 слово (сетевые
      // настройки + идентификация) и запись RW-полей одним пакетом.
      virtual void ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Приём ПКУ (0x3003_0000): чтение длительностей ПКУ (RO).
      virtual void ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Настройка ПКУ (0x3003_0080): режим приёма каждого ПКУ (RW).
      virtual void SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Выдача РК (0x3002): запись длительности по индексу.
      virtual void SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* AsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* PrepareAsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* AsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* PrepareAsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>* AsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadMemoryResponse>* PrepareAsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* AsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* PrepareAsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>* AsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::ReadPkuResponse>* PrepareAsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* AsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* PrepareAsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* AsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::StandardResponse>* PrepareAsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>* AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pku::driver::v1::VersionInfo>* PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> AsyncCheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(AsyncCheckConnectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> PrepareAsyncCheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(PrepareAsyncCheckConnectionRaw(context, request, cq));
    }
    ::grpc::Status GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> AsyncGetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(AsyncGetHardwareStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> PrepareAsyncGetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(PrepareAsyncGetHardwareStatusRaw(context, request, cq));
    }
    ::grpc::Status ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::ReadMemoryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>> AsyncReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>>(AsyncReadMainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>> PrepareAsyncReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>>(PrepareAsyncReadMainInfoRaw(context, request, cq));
    }
    ::grpc::Status WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::pku::driver::v1::StandardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> AsyncWriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(AsyncWriteMainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> PrepareAsyncWriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(PrepareAsyncWriteMainInfoRaw(context, request, cq));
    }
    ::grpc::Status ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::pku::driver::v1::ReadPkuResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>> AsyncReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>>(AsyncReadPkuRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>> PrepareAsyncReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>>(PrepareAsyncReadPkuRaw(context, request, cq));
    }
    ::grpc::Status SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::pku::driver::v1::StandardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> AsyncSetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(AsyncSetPkuModeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> PrepareAsyncSetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(PrepareAsyncSetPkuModeRaw(context, request, cq));
    }
    ::grpc::Status SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::pku::driver::v1::StandardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> AsyncSendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(AsyncSendRkByIndexRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>> PrepareAsyncSendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>>(PrepareAsyncSendRkByIndexRaw(context, request, cq));
    }
    ::grpc::Status GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::VersionInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>> AsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>>(AsyncGetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>> PrepareAsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>>(PrepareAsyncGetVersionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) override;
      void GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, std::function<void(::grpc::Status)>) override;
      void ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) override;
      void WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, std::function<void(::grpc::Status)>) override;
      void ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) override;
      void SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)>) override;
      void SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, std::function<void(::grpc::Status)>) override;
      void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* AsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PrepareAsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* AsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PrepareAsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>* AsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>* PrepareAsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* AsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PrepareAsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>* AsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>* PrepareAsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* AsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PrepareAsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* AsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PrepareAsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>* AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>* PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckConnection_;
    const ::grpc::internal::RpcMethod rpcmethod_GetHardwareStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadMainInfo_;
    const ::grpc::internal::RpcMethod rpcmethod_WriteMainInfo_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadPku_;
    const ::grpc::internal::RpcMethod rpcmethod_SetPkuMode_;
    const ::grpc::internal::RpcMethod rpcmethod_SendRkByIndex_;
    const ::grpc::internal::RpcMethod rpcmethod_GetVersion_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckConnection(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response);
    // Статус железки: читает основную информацию пульта; success=true, если
    // ответ получен и без ошибок (пульт доступен), иначе false + причина.
    virtual ::grpc::Status GetHardwareStatus(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response);
    // Основная информация пульта (0x0000): чтение блока 151 слово (сетевые
    // настройки + идентификация) и запись RW-полей одним пакетом.
    virtual ::grpc::Status ReadMainInfo(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response);
    virtual ::grpc::Status WriteMainInfo(::grpc::ServerContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response);
    // Приём ПКУ (0x3003_0000): чтение длительностей ПКУ (RO).
    virtual ::grpc::Status ReadPku(::grpc::ServerContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response);
    // Настройка ПКУ (0x3003_0080): режим приёма каждого ПКУ (RW).
    virtual ::grpc::Status SetPkuMode(::grpc::ServerContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response);
    // Выдача РК (0x3002): запись длительности по индексу.
    virtual ::grpc::Status SendRkByIndex(::grpc::ServerContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response);
    virtual ::grpc::Status GetVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckConnection() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckConnection(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::StandardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHardwareStatus(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::StandardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadMainInfo(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::ReadMemoryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteMainInfo(::grpc::ServerContext* context, ::pku::driver::v1::WriteMainInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::StandardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadPku() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadPku(::grpc::ServerContext* context, ::pku::driver::v1::ReadPkuRequest* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::ReadPkuResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetPkuMode(::grpc::ServerContext* context, ::pku::driver::v1::SetPkuModeRequest* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::StandardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendRkByIndex(::grpc::ServerContext* context, ::pku::driver::v1::SendRkByIndexRequest* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::StandardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVersion() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVersion(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::pku::driver::v1::VersionInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckConnection<WithAsyncMethod_GetHardwareStatus<WithAsyncMethod_ReadMainInfo<WithAsyncMethod_WriteMainInfo<WithAsyncMethod_ReadPku<WithAsyncMethod_SetPkuMode<WithAsyncMethod_SendRkByIndex<WithAsyncMethod_GetVersion<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckConnection() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response) { return this->CheckConnection(context, request, response); }));}
    void SetMessageAllocatorFor_CheckConnection(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckConnection(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response) { return this->GetHardwareStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetHardwareStatus(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHardwareStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response) { return this->ReadMainInfo(context, request, response); }));}
    void SetMessageAllocatorFor_ReadMainInfo(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadMainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response) { return this->WriteMainInfo(context, request, response); }));}
    void SetMessageAllocatorFor_WriteMainInfo(
        ::grpc::MessageAllocator< ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteMainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadPku() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response) { return this->ReadPku(context, request, response); }));}
    void SetMessageAllocatorFor_ReadPku(
        ::grpc::MessageAllocator< ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadPku(
      ::grpc::CallbackServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response) { return this->SetPkuMode(context, request, response); }));}
    void SetMessageAllocatorFor_SetPkuMode(
        ::grpc::MessageAllocator< ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetPkuMode(
      ::grpc::CallbackServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response) { return this->SendRkByIndex(context, request, response); }));}
    void SetMessageAllocatorFor_SendRkByIndex(
        ::grpc::MessageAllocator< ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendRkByIndex(
      ::grpc::CallbackServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVersion() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response) { return this->GetVersion(context, request, response); }));}
    void SetMessageAllocatorFor_GetVersion(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckConnection<WithCallbackMethod_GetHardwareStatus<WithCallbackMethod_ReadMainInfo<WithCallbackMethod_WriteMainInfo<WithCallbackMethod_ReadPku<WithCallbackMethod_SetPkuMode<WithCallbackMethod_SendRkByIndex<WithCallbackMethod_GetVersion<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckConnection() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadPku() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVersion() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckConnection() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckConnection(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHardwareStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadMainInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteMainInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadPku() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadPku(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetPkuMode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendRkByIndex(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVersion() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVersion(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckConnection() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckConnection(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckConnection(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetHardwareStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHardwareStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadMainInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadMainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WriteMainInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteMainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadPku() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadPku(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadPku(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetPkuMode(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetPkuMode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendRkByIndex(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendRkByIndex(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVersion() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVersion(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckConnection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckConnection() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>* streamer) {
                       return this->StreamedCheckConnection(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckConnection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckConnection(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckConnection(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::pku::driver::v1::StandardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetHardwareStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetHardwareStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse>* streamer) {
                       return this->StreamedGetHardwareStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetHardwareStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetHardwareStatus(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetHardwareStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::pku::driver::v1::StandardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadMainInfo() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse>* streamer) {
                       return this->StreamedReadMainInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadMainInfo(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::ReadMemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadMainInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::pku::driver::v1::ReadMemoryResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WriteMainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WriteMainInfo() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse>* streamer) {
                       return this->StreamedWriteMainInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WriteMainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WriteMainInfo(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::WriteMainInfoRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWriteMainInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pku::driver::v1::WriteMainInfoRequest,::pku::driver::v1::StandardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadPku : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadPku() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse>* streamer) {
                       return this->StreamedReadPku(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadPku() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadPku(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::ReadPkuRequest* /*request*/, ::pku::driver::v1::ReadPkuResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadPku(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pku::driver::v1::ReadPkuRequest,::pku::driver::v1::ReadPkuResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetPkuMode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetPkuMode() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse>* streamer) {
                       return this->StreamedSetPkuMode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetPkuMode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetPkuMode(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SetPkuModeRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetPkuMode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pku::driver::v1::SetPkuModeRequest,::pku::driver::v1::StandardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendRkByIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendRkByIndex() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse>* streamer) {
                       return this->StreamedSendRkByIndex(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendRkByIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendRkByIndex(::grpc::ServerContext* /*context*/, const ::pku::driver::v1::SendRkByIndexRequest* /*request*/, ::pku::driver::v1::StandardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendRkByIndex(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pku::driver::v1::SendRkByIndexRequest,::pku::driver::v1::StandardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVersion() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo>* streamer) {
                       return this->StreamedGetVersion(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::pku::driver::v1::VersionInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVersion(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::pku::driver::v1::VersionInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckConnection<WithStreamedUnaryMethod_GetHardwareStatus<WithStreamedUnaryMethod_ReadMainInfo<WithStreamedUnaryMethod_WriteMainInfo<WithStreamedUnaryMethod_ReadPku<WithStreamedUnaryMethod_SetPkuMode<WithStreamedUnaryMethod_SendRkByIndex<WithStreamedUnaryMethod_GetVersion<Service > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckConnection<WithStreamedUnaryMethod_GetHardwareStatus<WithStreamedUnaryMethod_ReadMainInfo<WithStreamedUnaryMethod_WriteMainInfo<WithStreamedUnaryMethod_ReadPku<WithStreamedUnaryMethod_SetPkuMode<WithStreamedUnaryMethod_SendRkByIndex<WithStreamedUnaryMethod_GetVersion<Service > > > > > > > > StreamedService;
};

}  // namespace v1
}  // namespace driver
}  // namespace pku


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_pku_5fdriver_2eproto__INCLUDED
