// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pku_driver.proto

#include "pku_driver.pb.h"
#include "pku_driver.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace pku {
namespace driver {
namespace v1 {

static const char* PkuDriver_method_names[] = {
  "/pku.driver.v1.PkuDriver/CheckConnection",
  "/pku.driver.v1.PkuDriver/GetHardwareStatus",
  "/pku.driver.v1.PkuDriver/ReadMainInfo",
  "/pku.driver.v1.PkuDriver/WriteMainInfo",
  "/pku.driver.v1.PkuDriver/ReadPku",
  "/pku.driver.v1.PkuDriver/SetPkuMode",
  "/pku.driver.v1.PkuDriver/SendRkByIndex",
  "/pku.driver.v1.PkuDriver/GetVersion",
};

std::unique_ptr< PkuDriver::Stub> PkuDriver::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PkuDriver::Stub> stub(new PkuDriver::Stub(channel, options));
  return stub;
}

PkuDriver::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckConnection_(PkuDriver_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetHardwareStatus_(PkuDriver_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadMainInfo_(PkuDriver_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteMainInfo_(PkuDriver_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadPku_(PkuDriver_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPkuMode_(PkuDriver_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendRkByIndex_(PkuDriver_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetVersion_(PkuDriver_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PkuDriver::Stub::CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckConnection_, context, request, response);
}

void PkuDriver::Stub::async::CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckConnection_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::CheckConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::PrepareAsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::StandardResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckConnection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::AsyncCheckConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckConnectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::StandardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHardwareStatus_, context, request, response);
}

void PkuDriver::Stub::async::GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHardwareStatus_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::GetHardwareStatus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHardwareStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::PrepareAsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::StandardResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHardwareStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::AsyncGetHardwareStatusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHardwareStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::ReadMemoryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadMainInfo_, context, request, response);
}

void PkuDriver::Stub::async::ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadMainInfo_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::ReadMainInfo(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadMainInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>* PkuDriver::Stub::PrepareAsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::ReadMemoryResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadMainInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadMemoryResponse>* PkuDriver::Stub::AsyncReadMainInfoRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadMainInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::pku::driver::v1::StandardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteMainInfo_, context, request, response);
}

void PkuDriver::Stub::async::WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteMainInfo_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::WriteMainInfo(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteMainInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::PrepareAsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::StandardResponse, ::pku::driver::v1::WriteMainInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteMainInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::AsyncWriteMainInfoRaw(::grpc::ClientContext* context, const ::pku::driver::v1::WriteMainInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteMainInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::pku::driver::v1::ReadPkuResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadPku_, context, request, response);
}

void PkuDriver::Stub::async::ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadPku_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::ReadPku(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadPku_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>* PkuDriver::Stub::PrepareAsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::ReadPkuResponse, ::pku::driver::v1::ReadPkuRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadPku_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::ReadPkuResponse>* PkuDriver::Stub::AsyncReadPkuRaw(::grpc::ClientContext* context, const ::pku::driver::v1::ReadPkuRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadPkuRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::pku::driver::v1::StandardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPkuMode_, context, request, response);
}

void PkuDriver::Stub::async::SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPkuMode_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::SetPkuMode(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPkuMode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::PrepareAsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::StandardResponse, ::pku::driver::v1::SetPkuModeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPkuMode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::AsyncSetPkuModeRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SetPkuModeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPkuModeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::pku::driver::v1::StandardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendRkByIndex_, context, request, response);
}

void PkuDriver::Stub::async::SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRkByIndex_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::SendRkByIndex(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRkByIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::PrepareAsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::StandardResponse, ::pku::driver::v1::SendRkByIndexRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendRkByIndex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::StandardResponse>* PkuDriver::Stub::AsyncSendRkByIndexRaw(::grpc::ClientContext* context, const ::pku::driver::v1::SendRkByIndexRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRkByIndexRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PkuDriver::Stub::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::pku::driver::v1::VersionInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVersion_, context, request, response);
}

void PkuDriver::Stub::async::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, std::move(f));
}

void PkuDriver::Stub::async::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>* PkuDriver::Stub::PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pku::driver::v1::VersionInfo, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pku::driver::v1::VersionInfo>* PkuDriver::Stub::AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

PkuDriver::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::pku::driver::v1::StandardResponse* resp) {
               return service->CheckConnection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::google::protobuf::Empty, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::pku::driver::v1::StandardResponse* resp) {
               return service->GetHardwareStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::google::protobuf::Empty, ::pku::driver::v1::ReadMemoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::pku::driver::v1::ReadMemoryResponse* resp) {
               return service->ReadMainInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::pku::driver::v1::WriteMainInfoRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pku::driver::v1::WriteMainInfoRequest* req,
             ::pku::driver::v1::StandardResponse* resp) {
               return service->WriteMainInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::pku::driver::v1::ReadPkuRequest, ::pku::driver::v1::ReadPkuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pku::driver::v1::ReadPkuRequest* req,
             ::pku::driver::v1::ReadPkuResponse* resp) {
               return service->ReadPku(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::pku::driver::v1::SetPkuModeRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pku::driver::v1::SetPkuModeRequest* req,
             ::pku::driver::v1::StandardResponse* resp) {
               return service->SetPkuMode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::pku::driver::v1::SendRkByIndexRequest, ::pku::driver::v1::StandardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pku::driver::v1::SendRkByIndexRequest* req,
             ::pku::driver::v1::StandardResponse* resp) {
               return service->SendRkByIndex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PkuDriver_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PkuDriver::Service, ::google::protobuf::Empty, ::pku::driver::v1::VersionInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PkuDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::pku::driver::v1::VersionInfo* resp) {
               return service->GetVersion(ctx, req, resp);
             }, this)));
}

PkuDriver::Service::~Service() {
}

::grpc::Status PkuDriver::Service::CheckConnection(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::GetHardwareStatus(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::StandardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::ReadMainInfo(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::ReadMemoryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::WriteMainInfo(::grpc::ServerContext* context, const ::pku::driver::v1::WriteMainInfoRequest* request, ::pku::driver::v1::StandardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::ReadPku(::grpc::ServerContext* context, const ::pku::driver::v1::ReadPkuRequest* request, ::pku::driver::v1::ReadPkuResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::SetPkuMode(::grpc::ServerContext* context, const ::pku::driver::v1::SetPkuModeRequest* request, ::pku::driver::v1::StandardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::SendRkByIndex(::grpc::ServerContext* context, const ::pku::driver::v1::SendRkByIndexRequest* request, ::pku::driver::v1::StandardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PkuDriver::Service::GetVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::pku::driver::v1::VersionInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pku
}  // namespace driver
}  // namespace v1
#include <grpcpp/ports_undef.inc>

