// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rs485_driver.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rs485_5fdriver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rs485_5fdriver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rs485_5fdriver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rs485_5fdriver_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rs485_5fdriver_2eproto;
namespace rs485 {
namespace driver {
namespace v1 {
class ReceiveDataResponse;
struct ReceiveDataResponseDefaultTypeInternal;
extern ReceiveDataResponseDefaultTypeInternal _ReceiveDataResponse_default_instance_;
class SendDataRequest;
struct SendDataRequestDefaultTypeInternal;
extern SendDataRequestDefaultTypeInternal _SendDataRequest_default_instance_;
class SendDataResponce;
struct SendDataResponceDefaultTypeInternal;
extern SendDataResponceDefaultTypeInternal _SendDataResponce_default_instance_;
}  // namespace v1
}  // namespace driver
}  // namespace rs485
PROTOBUF_NAMESPACE_OPEN
template<> ::rs485::driver::v1::ReceiveDataResponse* Arena::CreateMaybeMessage<::rs485::driver::v1::ReceiveDataResponse>(Arena*);
template<> ::rs485::driver::v1::SendDataRequest* Arena::CreateMaybeMessage<::rs485::driver::v1::SendDataRequest>(Arena*);
template<> ::rs485::driver::v1::SendDataResponce* Arena::CreateMaybeMessage<::rs485::driver::v1::SendDataResponce>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rs485 {
namespace driver {
namespace v1 {

enum PultErrors : int {
  NO_ERROR = 0,
  WRONG_BRIDGE_ID = 1,
  NO_REPLY = 2,
  WRONG_INTERFACE = 3,
  TIMEOUT = 4,
  EMPTY_BUFFER = 5,
  WRONG_PARAM = 6,
  PultErrors_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PultErrors_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PultErrors_IsValid(int value);
constexpr PultErrors PultErrors_MIN = NO_ERROR;
constexpr PultErrors PultErrors_MAX = WRONG_PARAM;
constexpr int PultErrors_ARRAYSIZE = PultErrors_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PultErrors_descriptor();
template<typename T>
inline const std::string& PultErrors_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PultErrors>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PultErrors_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PultErrors_descriptor(), enum_t_value);
}
inline bool PultErrors_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PultErrors* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PultErrors>(
    PultErrors_descriptor(), name, value);
}
// ===================================================================

class SendDataRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rs485.driver.v1.SendDataRequest) */ {
 public:
  inline SendDataRequest() : SendDataRequest(nullptr) {}
  ~SendDataRequest() override;
  explicit PROTOBUF_CONSTEXPR SendDataRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendDataRequest(const SendDataRequest& from);
  SendDataRequest(SendDataRequest&& from) noexcept
    : SendDataRequest() {
    *this = ::std::move(from);
  }

  inline SendDataRequest& operator=(const SendDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendDataRequest& operator=(SendDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendDataRequest* internal_default_instance() {
    return reinterpret_cast<const SendDataRequest*>(
               &_SendDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SendDataRequest& a, SendDataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SendDataRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendDataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendDataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendDataRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendDataRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendDataRequest& from) {
    SendDataRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendDataRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rs485.driver.v1.SendDataRequest";
  }
  protected:
  explicit SendDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kChannelIdFieldNumber = 1,
  };
  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint32 channel_id = 1;
  void clear_channel_id();
  uint32_t channel_id() const;
  void set_channel_id(uint32_t value);
  private:
  uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rs485.driver.v1.SendDataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    uint32_t channel_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rs485_5fdriver_2eproto;
};
// -------------------------------------------------------------------

class SendDataResponce final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rs485.driver.v1.SendDataResponce) */ {
 public:
  inline SendDataResponce() : SendDataResponce(nullptr) {}
  ~SendDataResponce() override;
  explicit PROTOBUF_CONSTEXPR SendDataResponce(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendDataResponce(const SendDataResponce& from);
  SendDataResponce(SendDataResponce&& from) noexcept
    : SendDataResponce() {
    *this = ::std::move(from);
  }

  inline SendDataResponce& operator=(const SendDataResponce& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendDataResponce& operator=(SendDataResponce&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendDataResponce& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendDataResponce* internal_default_instance() {
    return reinterpret_cast<const SendDataResponce*>(
               &_SendDataResponce_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendDataResponce& a, SendDataResponce& b) {
    a.Swap(&b);
  }
  inline void Swap(SendDataResponce* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendDataResponce* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendDataResponce* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendDataResponce>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendDataResponce& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendDataResponce& from) {
    SendDataResponce::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendDataResponce* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rs485.driver.v1.SendDataResponce";
  }
  protected:
  explicit SendDataResponce(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kChannelIdFieldNumber = 2,
    kErrorMessageFieldNumber = 3,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint32 channel_id = 2;
  void clear_channel_id();
  uint32_t channel_id() const;
  void set_channel_id(uint32_t value);
  private:
  uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(uint32_t value);
  public:

  // .rs485.driver.v1.PultErrors error_message = 3;
  void clear_error_message();
  ::rs485::driver::v1::PultErrors error_message() const;
  void set_error_message(::rs485::driver::v1::PultErrors value);
  private:
  ::rs485::driver::v1::PultErrors _internal_error_message() const;
  void _internal_set_error_message(::rs485::driver::v1::PultErrors value);
  public:

  // @@protoc_insertion_point(class_scope:rs485.driver.v1.SendDataResponce)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    uint32_t channel_id_;
    int error_message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rs485_5fdriver_2eproto;
};
// -------------------------------------------------------------------

class ReceiveDataResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rs485.driver.v1.ReceiveDataResponse) */ {
 public:
  inline ReceiveDataResponse() : ReceiveDataResponse(nullptr) {}
  ~ReceiveDataResponse() override;
  explicit PROTOBUF_CONSTEXPR ReceiveDataResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReceiveDataResponse(const ReceiveDataResponse& from);
  ReceiveDataResponse(ReceiveDataResponse&& from) noexcept
    : ReceiveDataResponse() {
    *this = ::std::move(from);
  }

  inline ReceiveDataResponse& operator=(const ReceiveDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReceiveDataResponse& operator=(ReceiveDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReceiveDataResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReceiveDataResponse* internal_default_instance() {
    return reinterpret_cast<const ReceiveDataResponse*>(
               &_ReceiveDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReceiveDataResponse& a, ReceiveDataResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ReceiveDataResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReceiveDataResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReceiveDataResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReceiveDataResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReceiveDataResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReceiveDataResponse& from) {
    ReceiveDataResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReceiveDataResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rs485.driver.v1.ReceiveDataResponse";
  }
  protected:
  explicit ReceiveDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kSuccessFieldNumber = 1,
    kChannelIdFieldNumber = 2,
    kErrorMessageFieldNumber = 4,
  };
  // repeated bytes data = 3;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  const std::string& data(int index) const;
  std::string* mutable_data(int index);
  void set_data(int index, const std::string& value);
  void set_data(int index, std::string&& value);
  void set_data(int index, const char* value);
  void set_data(int index, const void* value, size_t size);
  std::string* add_data();
  void add_data(const std::string& value);
  void add_data(std::string&& value);
  void add_data(const char* value);
  void add_data(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_data();
  private:
  const std::string& _internal_data(int index) const;
  std::string* _internal_add_data();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint32 channel_id = 2;
  void clear_channel_id();
  uint32_t channel_id() const;
  void set_channel_id(uint32_t value);
  private:
  uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(uint32_t value);
  public:

  // .rs485.driver.v1.PultErrors error_message = 4;
  void clear_error_message();
  ::rs485::driver::v1::PultErrors error_message() const;
  void set_error_message(::rs485::driver::v1::PultErrors value);
  private:
  ::rs485::driver::v1::PultErrors _internal_error_message() const;
  void _internal_set_error_message(::rs485::driver::v1::PultErrors value);
  public:

  // @@protoc_insertion_point(class_scope:rs485.driver.v1.ReceiveDataResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> data_;
    bool success_;
    uint32_t channel_id_;
    int error_message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rs485_5fdriver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SendDataRequest

// uint32 channel_id = 1;
inline void SendDataRequest::clear_channel_id() {
  _impl_.channel_id_ = 0u;
}
inline uint32_t SendDataRequest::_internal_channel_id() const {
  return _impl_.channel_id_;
}
inline uint32_t SendDataRequest::channel_id() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.SendDataRequest.channel_id)
  return _internal_channel_id();
}
inline void SendDataRequest::_internal_set_channel_id(uint32_t value) {
  
  _impl_.channel_id_ = value;
}
inline void SendDataRequest::set_channel_id(uint32_t value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.SendDataRequest.channel_id)
}

// bytes data = 2;
inline void SendDataRequest::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& SendDataRequest::data() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.SendDataRequest.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SendDataRequest::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rs485.driver.v1.SendDataRequest.data)
}
inline std::string* SendDataRequest::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:rs485.driver.v1.SendDataRequest.data)
  return _s;
}
inline const std::string& SendDataRequest::_internal_data() const {
  return _impl_.data_.Get();
}
inline void SendDataRequest::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* SendDataRequest::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* SendDataRequest::release_data() {
  // @@protoc_insertion_point(field_release:rs485.driver.v1.SendDataRequest.data)
  return _impl_.data_.Release();
}
inline void SendDataRequest::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rs485.driver.v1.SendDataRequest.data)
}

// -------------------------------------------------------------------

// SendDataResponce

// bool success = 1;
inline void SendDataResponce::clear_success() {
  _impl_.success_ = false;
}
inline bool SendDataResponce::_internal_success() const {
  return _impl_.success_;
}
inline bool SendDataResponce::success() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.SendDataResponce.success)
  return _internal_success();
}
inline void SendDataResponce::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SendDataResponce::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.SendDataResponce.success)
}

// uint32 channel_id = 2;
inline void SendDataResponce::clear_channel_id() {
  _impl_.channel_id_ = 0u;
}
inline uint32_t SendDataResponce::_internal_channel_id() const {
  return _impl_.channel_id_;
}
inline uint32_t SendDataResponce::channel_id() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.SendDataResponce.channel_id)
  return _internal_channel_id();
}
inline void SendDataResponce::_internal_set_channel_id(uint32_t value) {
  
  _impl_.channel_id_ = value;
}
inline void SendDataResponce::set_channel_id(uint32_t value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.SendDataResponce.channel_id)
}

// .rs485.driver.v1.PultErrors error_message = 3;
inline void SendDataResponce::clear_error_message() {
  _impl_.error_message_ = 0;
}
inline ::rs485::driver::v1::PultErrors SendDataResponce::_internal_error_message() const {
  return static_cast< ::rs485::driver::v1::PultErrors >(_impl_.error_message_);
}
inline ::rs485::driver::v1::PultErrors SendDataResponce::error_message() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.SendDataResponce.error_message)
  return _internal_error_message();
}
inline void SendDataResponce::_internal_set_error_message(::rs485::driver::v1::PultErrors value) {
  
  _impl_.error_message_ = value;
}
inline void SendDataResponce::set_error_message(::rs485::driver::v1::PultErrors value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.SendDataResponce.error_message)
}

// -------------------------------------------------------------------

// ReceiveDataResponse

// bool success = 1;
inline void ReceiveDataResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ReceiveDataResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ReceiveDataResponse::success() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.ReceiveDataResponse.success)
  return _internal_success();
}
inline void ReceiveDataResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ReceiveDataResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.ReceiveDataResponse.success)
}

// uint32 channel_id = 2;
inline void ReceiveDataResponse::clear_channel_id() {
  _impl_.channel_id_ = 0u;
}
inline uint32_t ReceiveDataResponse::_internal_channel_id() const {
  return _impl_.channel_id_;
}
inline uint32_t ReceiveDataResponse::channel_id() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.ReceiveDataResponse.channel_id)
  return _internal_channel_id();
}
inline void ReceiveDataResponse::_internal_set_channel_id(uint32_t value) {
  
  _impl_.channel_id_ = value;
}
inline void ReceiveDataResponse::set_channel_id(uint32_t value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.ReceiveDataResponse.channel_id)
}

// repeated bytes data = 3;
inline int ReceiveDataResponse::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int ReceiveDataResponse::data_size() const {
  return _internal_data_size();
}
inline void ReceiveDataResponse::clear_data() {
  _impl_.data_.Clear();
}
inline std::string* ReceiveDataResponse::add_data() {
  std::string* _s = _internal_add_data();
  // @@protoc_insertion_point(field_add_mutable:rs485.driver.v1.ReceiveDataResponse.data)
  return _s;
}
inline const std::string& ReceiveDataResponse::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline const std::string& ReceiveDataResponse::data(int index) const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.ReceiveDataResponse.data)
  return _internal_data(index);
}
inline std::string* ReceiveDataResponse::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:rs485.driver.v1.ReceiveDataResponse.data)
  return _impl_.data_.Mutable(index);
}
inline void ReceiveDataResponse::set_data(int index, const std::string& value) {
  _impl_.data_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::set_data(int index, std::string&& value) {
  _impl_.data_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::set_data(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.data_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::set_data(int index, const void* value, size_t size) {
  _impl_.data_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:rs485.driver.v1.ReceiveDataResponse.data)
}
inline std::string* ReceiveDataResponse::_internal_add_data() {
  return _impl_.data_.Add();
}
inline void ReceiveDataResponse::add_data(const std::string& value) {
  _impl_.data_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::add_data(std::string&& value) {
  _impl_.data_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::add_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.data_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:rs485.driver.v1.ReceiveDataResponse.data)
}
inline void ReceiveDataResponse::add_data(const void* value, size_t size) {
  _impl_.data_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:rs485.driver.v1.ReceiveDataResponse.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ReceiveDataResponse::data() const {
  // @@protoc_insertion_point(field_list:rs485.driver.v1.ReceiveDataResponse.data)
  return _impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ReceiveDataResponse::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:rs485.driver.v1.ReceiveDataResponse.data)
  return &_impl_.data_;
}

// .rs485.driver.v1.PultErrors error_message = 4;
inline void ReceiveDataResponse::clear_error_message() {
  _impl_.error_message_ = 0;
}
inline ::rs485::driver::v1::PultErrors ReceiveDataResponse::_internal_error_message() const {
  return static_cast< ::rs485::driver::v1::PultErrors >(_impl_.error_message_);
}
inline ::rs485::driver::v1::PultErrors ReceiveDataResponse::error_message() const {
  // @@protoc_insertion_point(field_get:rs485.driver.v1.ReceiveDataResponse.error_message)
  return _internal_error_message();
}
inline void ReceiveDataResponse::_internal_set_error_message(::rs485::driver::v1::PultErrors value) {
  
  _impl_.error_message_ = value;
}
inline void ReceiveDataResponse::set_error_message(::rs485::driver::v1::PultErrors value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:rs485.driver.v1.ReceiveDataResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace driver
}  // namespace rs485

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::rs485::driver::v1::PultErrors> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rs485::driver::v1::PultErrors>() {
  return ::rs485::driver::v1::PultErrors_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rs485_5fdriver_2eproto
