// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rs485_driver.proto

#include "rs485_driver.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rs485 {
namespace driver {
namespace v1 {
PROTOBUF_CONSTEXPR SendDataRequest::SendDataRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.channel_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendDataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendDataRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendDataRequestDefaultTypeInternal() {}
  union {
    SendDataRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendDataRequestDefaultTypeInternal _SendDataRequest_default_instance_;
PROTOBUF_CONSTEXPR SendDataResponce::SendDataResponce(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.channel_id_)*/0u
  , /*decltype(_impl_.error_message_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SendDataResponceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SendDataResponceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SendDataResponceDefaultTypeInternal() {}
  union {
    SendDataResponce _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SendDataResponceDefaultTypeInternal _SendDataResponce_default_instance_;
PROTOBUF_CONSTEXPR ReceiveDataResponse::ReceiveDataResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.channel_id_)*/0u
  , /*decltype(_impl_.error_message_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReceiveDataResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReceiveDataResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReceiveDataResponseDefaultTypeInternal() {}
  union {
    ReceiveDataResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReceiveDataResponseDefaultTypeInternal _ReceiveDataResponse_default_instance_;
}  // namespace v1
}  // namespace driver
}  // namespace rs485
static ::_pb::Metadata file_level_metadata_rs485_5fdriver_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_rs485_5fdriver_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_rs485_5fdriver_2eproto = nullptr;

const uint32_t TableStruct_rs485_5fdriver_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataRequest, _impl_.channel_id_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataRequest, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataResponce, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataResponce, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataResponce, _impl_.channel_id_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::SendDataResponce, _impl_.error_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::ReceiveDataResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::ReceiveDataResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::ReceiveDataResponse, _impl_.channel_id_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::ReceiveDataResponse, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::rs485::driver::v1::ReceiveDataResponse, _impl_.error_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rs485::driver::v1::SendDataRequest)},
  { 8, -1, -1, sizeof(::rs485::driver::v1::SendDataResponce)},
  { 17, -1, -1, sizeof(::rs485::driver::v1::ReceiveDataResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rs485::driver::v1::_SendDataRequest_default_instance_._instance,
  &::rs485::driver::v1::_SendDataResponce_default_instance_._instance,
  &::rs485::driver::v1::_ReceiveDataResponse_default_instance_._instance,
};

const char descriptor_table_protodef_rs485_5fdriver_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022rs485_driver.proto\022\017rs485.driver.v1\032\033g"
  "oogle/protobuf/empty.proto\"3\n\017SendDataRe"
  "quest\022\022\n\nchannel_id\030\001 \001(\r\022\014\n\004data\030\002 \001(\014\""
  "k\n\020SendDataResponce\022\017\n\007success\030\001 \001(\010\022\022\n\n"
  "channel_id\030\002 \001(\r\0222\n\rerror_message\030\003 \001(\0162"
  "\033.rs485.driver.v1.PultErrors\"|\n\023ReceiveD"
  "ataResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nchannel_"
  "id\030\002 \001(\r\022\014\n\004data\030\003 \003(\014\0222\n\rerror_message\030"
  "\004 \001(\0162\033.rs485.driver.v1.PultErrors*\202\001\n\nP"
  "ultErrors\022\014\n\010NO_ERROR\020\000\022\023\n\017WRONG_BRIDGE_"
  "ID\020\001\022\014\n\010NO_REPLY\020\002\022\023\n\017WRONG_INTERFACE\020\003\022"
  "\013\n\007TIMEOUT\020\004\022\020\n\014EMPTY_BUFFER\020\005\022\017\n\013WRONG_"
  "PARAM\020\0062\257\001\n\013Rs485Driver\022S\n\010SendData\022 .rs"
  "485.driver.v1.SendDataRequest\032!.rs485.dr"
  "iver.v1.SendDataResponce(\0010\001\022K\n\tSubscrib"
  "e\022\026.google.protobuf.Empty\032$.rs485.driver"
  ".v1.ReceiveDataResponse0\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_rs485_5fdriver_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_rs485_5fdriver_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rs485_5fdriver_2eproto = {
    false, false, 673, descriptor_table_protodef_rs485_5fdriver_2eproto,
    "rs485_driver.proto",
    &descriptor_table_rs485_5fdriver_2eproto_once, descriptor_table_rs485_5fdriver_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_rs485_5fdriver_2eproto::offsets,
    file_level_metadata_rs485_5fdriver_2eproto, file_level_enum_descriptors_rs485_5fdriver_2eproto,
    file_level_service_descriptors_rs485_5fdriver_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rs485_5fdriver_2eproto_getter() {
  return &descriptor_table_rs485_5fdriver_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rs485_5fdriver_2eproto(&descriptor_table_rs485_5fdriver_2eproto);
namespace rs485 {
namespace driver {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PultErrors_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_rs485_5fdriver_2eproto);
  return file_level_enum_descriptors_rs485_5fdriver_2eproto[0];
}
bool PultErrors_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class SendDataRequest::_Internal {
 public:
};

SendDataRequest::SendDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rs485.driver.v1.SendDataRequest)
}
SendDataRequest::SendDataRequest(const SendDataRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendDataRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.channel_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.channel_id_ = from._impl_.channel_id_;
  // @@protoc_insertion_point(copy_constructor:rs485.driver.v1.SendDataRequest)
}

inline void SendDataRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.channel_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SendDataRequest::~SendDataRequest() {
  // @@protoc_insertion_point(destructor:rs485.driver.v1.SendDataRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendDataRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void SendDataRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rs485.driver.v1.SendDataRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _impl_.channel_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendDataRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 channel_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.channel_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendDataRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rs485.driver.v1.SendDataRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 channel_id = 1;
  if (this->_internal_channel_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_channel_id(), target);
  }

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rs485.driver.v1.SendDataRequest)
  return target;
}

size_t SendDataRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rs485.driver.v1.SendDataRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // uint32 channel_id = 1;
  if (this->_internal_channel_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_channel_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendDataRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendDataRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendDataRequest::GetClassData() const { return &_class_data_; }


void SendDataRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendDataRequest*>(&to_msg);
  auto& from = static_cast<const SendDataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rs485.driver.v1.SendDataRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_channel_id() != 0) {
    _this->_internal_set_channel_id(from._internal_channel_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendDataRequest::CopyFrom(const SendDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rs485.driver.v1.SendDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendDataRequest::IsInitialized() const {
  return true;
}

void SendDataRequest::InternalSwap(SendDataRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  swap(_impl_.channel_id_, other->_impl_.channel_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SendDataRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rs485_5fdriver_2eproto_getter, &descriptor_table_rs485_5fdriver_2eproto_once,
      file_level_metadata_rs485_5fdriver_2eproto[0]);
}

// ===================================================================

class SendDataResponce::_Internal {
 public:
};

SendDataResponce::SendDataResponce(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rs485.driver.v1.SendDataResponce)
}
SendDataResponce::SendDataResponce(const SendDataResponce& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SendDataResponce* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){}
    , decltype(_impl_.channel_id_){}
    , decltype(_impl_.error_message_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.error_message_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_message_));
  // @@protoc_insertion_point(copy_constructor:rs485.driver.v1.SendDataResponce)
}

inline void SendDataResponce::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.success_){false}
    , decltype(_impl_.channel_id_){0u}
    , decltype(_impl_.error_message_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SendDataResponce::~SendDataResponce() {
  // @@protoc_insertion_point(destructor:rs485.driver.v1.SendDataResponce)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SendDataResponce::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SendDataResponce::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SendDataResponce::Clear() {
// @@protoc_insertion_point(message_clear_start:rs485.driver.v1.SendDataResponce)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.error_message_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_message_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SendDataResponce::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 channel_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.channel_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .rs485.driver.v1.PultErrors error_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_error_message(static_cast<::rs485::driver::v1::PultErrors>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SendDataResponce::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rs485.driver.v1.SendDataResponce)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // uint32 channel_id = 2;
  if (this->_internal_channel_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_channel_id(), target);
  }

  // .rs485.driver.v1.PultErrors error_message = 3;
  if (this->_internal_error_message() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rs485.driver.v1.SendDataResponce)
  return target;
}

size_t SendDataResponce::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rs485.driver.v1.SendDataResponce)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // uint32 channel_id = 2;
  if (this->_internal_channel_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_channel_id());
  }

  // .rs485.driver.v1.PultErrors error_message = 3;
  if (this->_internal_error_message() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_error_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SendDataResponce::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SendDataResponce::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SendDataResponce::GetClassData() const { return &_class_data_; }


void SendDataResponce::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SendDataResponce*>(&to_msg);
  auto& from = static_cast<const SendDataResponce&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rs485.driver.v1.SendDataResponce)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_channel_id() != 0) {
    _this->_internal_set_channel_id(from._internal_channel_id());
  }
  if (from._internal_error_message() != 0) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SendDataResponce::CopyFrom(const SendDataResponce& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rs485.driver.v1.SendDataResponce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SendDataResponce::IsInitialized() const {
  return true;
}

void SendDataResponce::InternalSwap(SendDataResponce* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SendDataResponce, _impl_.error_message_)
      + sizeof(SendDataResponce::_impl_.error_message_)
      - PROTOBUF_FIELD_OFFSET(SendDataResponce, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SendDataResponce::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rs485_5fdriver_2eproto_getter, &descriptor_table_rs485_5fdriver_2eproto_once,
      file_level_metadata_rs485_5fdriver_2eproto[1]);
}

// ===================================================================

class ReceiveDataResponse::_Internal {
 public:
};

ReceiveDataResponse::ReceiveDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rs485.driver.v1.ReceiveDataResponse)
}
ReceiveDataResponse::ReceiveDataResponse(const ReceiveDataResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReceiveDataResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , decltype(_impl_.success_){}
    , decltype(_impl_.channel_id_){}
    , decltype(_impl_.error_message_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.error_message_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_message_));
  // @@protoc_insertion_point(copy_constructor:rs485.driver.v1.ReceiveDataResponse)
}

inline void ReceiveDataResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , decltype(_impl_.success_){false}
    , decltype(_impl_.channel_id_){0u}
    , decltype(_impl_.error_message_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ReceiveDataResponse::~ReceiveDataResponse() {
  // @@protoc_insertion_point(destructor:rs485.driver.v1.ReceiveDataResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReceiveDataResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedPtrField();
}

void ReceiveDataResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReceiveDataResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rs485.driver.v1.ReceiveDataResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  ::memset(&_impl_.success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.error_message_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.error_message_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReceiveDataResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 channel_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.channel_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated bytes data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_data();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .rs485.driver.v1.PultErrors error_message = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_error_message(static_cast<::rs485::driver::v1::PultErrors>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReceiveDataResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rs485.driver.v1.ReceiveDataResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // uint32 channel_id = 2;
  if (this->_internal_channel_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_channel_id(), target);
  }

  // repeated bytes data = 3;
  for (int i = 0, n = this->_internal_data_size(); i < n; i++) {
    const auto& s = this->_internal_data(i);
    target = stream->WriteBytes(3, s, target);
  }

  // .rs485.driver.v1.PultErrors error_message = 4;
  if (this->_internal_error_message() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rs485.driver.v1.ReceiveDataResponse)
  return target;
}

size_t ReceiveDataResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rs485.driver.v1.ReceiveDataResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes data = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.data_.size());
  for (int i = 0, n = _impl_.data_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      _impl_.data_.Get(i));
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // uint32 channel_id = 2;
  if (this->_internal_channel_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_channel_id());
  }

  // .rs485.driver.v1.PultErrors error_message = 4;
  if (this->_internal_error_message() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_error_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReceiveDataResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReceiveDataResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReceiveDataResponse::GetClassData() const { return &_class_data_; }


void ReceiveDataResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReceiveDataResponse*>(&to_msg);
  auto& from = static_cast<const ReceiveDataResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rs485.driver.v1.ReceiveDataResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_channel_id() != 0) {
    _this->_internal_set_channel_id(from._internal_channel_id());
  }
  if (from._internal_error_message() != 0) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReceiveDataResponse::CopyFrom(const ReceiveDataResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rs485.driver.v1.ReceiveDataResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReceiveDataResponse::IsInitialized() const {
  return true;
}

void ReceiveDataResponse::InternalSwap(ReceiveDataResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReceiveDataResponse, _impl_.error_message_)
      + sizeof(ReceiveDataResponse::_impl_.error_message_)
      - PROTOBUF_FIELD_OFFSET(ReceiveDataResponse, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReceiveDataResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rs485_5fdriver_2eproto_getter, &descriptor_table_rs485_5fdriver_2eproto_once,
      file_level_metadata_rs485_5fdriver_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace driver
}  // namespace rs485
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rs485::driver::v1::SendDataRequest*
Arena::CreateMaybeMessage< ::rs485::driver::v1::SendDataRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rs485::driver::v1::SendDataRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::rs485::driver::v1::SendDataResponce*
Arena::CreateMaybeMessage< ::rs485::driver::v1::SendDataResponce >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rs485::driver::v1::SendDataResponce >(arena);
}
template<> PROTOBUF_NOINLINE ::rs485::driver::v1::ReceiveDataResponse*
Arena::CreateMaybeMessage< ::rs485::driver::v1::ReceiveDataResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rs485::driver::v1::ReceiveDataResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
