@startuml c_1

!include <C4/C4_Context>

!theme plain

UpdateElementStyle(Person, $borderColor="#000000", $fontColor="#000000", $bgColor="#ffffff")
UpdateElementStyle(System, $borderColor="#000000", $fontColor="#000000", $bgColor="#ffffff")

Person(user, "Пользователь", "Взаимодействует с платой")

System(workplace, "Система взаимодействия с платой", "Позволяет обращаться к плате с разных драйверов")
System(board, "Плата", "Отвечает на запросы")

Rel(user, workplace, "Взаимодействует с платой")
Rel(workplace, board, "Отправляет запросы")

@enduml